"""
ComfyUI image generation endpoints:
  POST /api/v1/art/lineart   — upload sketch → lineart PNG (ControlNet)
  POST /api/v1/art/generate  — text prompt → image PNG (SDXL txt2img)
  POST /api/v1/art/compose   — sketch + question → advice text + reference image (JSON)
"""
from __future__ import annotations

import base64
import json
import random
import time
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, Form, HTTPException, UploadFile, File
from fastapi.responses import Response
from pydantic import BaseModel

from app.services import comfyui_client
from app.services.ai import art_service
from app.services.ai.ollama_client import DEFAULT_VISION_MODEL, DEFAULT_TEXT_MODEL

router = APIRouter(tags=["art-generate"])

# Project root is 3 parents above this file: api/ → app/ → backend/ → Craftflow/
# _WORKFLOW_DIR = (
#     Path(__file__).resolve().parents[3]
#     / "tools" / "Craftflow" / "diffusion" / "workflows"
# )
# 直接指向容器根目錄下的 diffusion，不管 .py 檔案在哪裡
# 根據你的 ls 指令結果，這才是正確的絕對路徑
_WORKFLOW_DIR = Path("/app/tools/Craftflow/diffusion/workflows")

# 為了讓開發時更靈活，可以加個 debug 檢查
if not _WORKFLOW_DIR.exists():
    # 本機開發路徑 (Windows)
    _WORKFLOW_DIR = Path(__file__).resolve().parents[3] / "tools" / "Craftflow" / "diffusion" / "workflows"

print(f"DEBUG: Found it! Path is: {_WORKFLOW_DIR}")


_DEFAULT_NEGATIVE = (
    "low quality, blurry, watermark, text, signature, bad anatomy, "
    "extra limbs, deformed, ugly, duplicate, worst quality"
)


# ── helpers ───────────────────────────────────────────────────────────────────

def _load_workflow(name: str) -> dict:
    path = _WORKFLOW_DIR / name
    with open(path, encoding="utf-8") as f:
        wf = json.load(f)
    wf.pop("_comment", None)
    return wf


def _run(workflow: dict) -> bytes:
    if not comfyui_client.is_available():
        raise HTTPException(
            status_code=503,
            detail="ComfyUI 未啟動，請先執行 ComfyUI (host.docker.internal:8188)。",
        )
    try:
        prompt_id = comfyui_client.submit_workflow(workflow)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=f"ComfyUI workflow 驗證失敗：{e}")
    try:
        filenames = comfyui_client.wait_for_result(prompt_id)
    except TimeoutError as e:
        raise HTTPException(status_code=504, detail=str(e))
    if not filenames:
        raise HTTPException(status_code=500, detail="ComfyUI 未回傳輸出圖片，請確認 workflow 設定。")
    return comfyui_client.download_image(filenames[0])


# ── endpoints ─────────────────────────────────────────────────────────────────

class OptimizePromptRequest(BaseModel):
    prompt: str
    model: str = DEFAULT_TEXT_MODEL

@router.post("/art/optimize-prompt", summary="AI 優化提示詞 (中文 → 英文 Tags)")
def optimize_prompt(req: OptimizePromptRequest):
    """
    Use Ollama to translate Chinese description and expand it into high-quality SDXL tags.
    """
    print(f"DEBUG: Optimizing prompt using model: {req.model}", flush=True)
    print(f"DEBUG: User prompt: {req.prompt}", flush=True)
    system_prompt = """你是一位專業的提示詞翻譯與優化助手。
任務：將用戶的中文描述精確轉化為 Stable Diffusion 標籤 (Tags)。

準則：
1. 精確優先：核心主體與動作必須完全符合中文描述。
2. 智慧補充：根據中文內容，適度補充細節標籤（例如：提到「少女」可補充「1girl, detailed face」；提到「夜晚」可補充「dark, night sky」）。
3. 格式要求：僅輸出純英文標籤，全部小寫，以逗號分隔。
4. 排除廢話：不要輸出任何解釋、標題、引號，只需給出 Tags 字符串。"""
    
    full_prompt = f"{system_prompt}\n\n用戶描述：{req.prompt}\n\n英文 Tags："
    start = time.time()
    optimized = art_service.ollama_client.generate(full_prompt, model=req.model)
    print(f"DEBUG: Optimization took {time.time() - start:.2f}s using {req.model}", flush=True)
    print(f"DEBUG: Optimized result: {optimized}", flush=True)
    
    return {"optimized": optimized}

@router.post("/art/lineart", summary="草稿→線稿 (ComfyUI ControlNet)")
async def lineart(file: Annotated[UploadFile, File(description="草稿圖片 (JPEG/PNG)")]):
    """
    Upload a sketch and receive clean lineart generated by ComfyUI.
    Requires: controlnet-scribble-sdxl-1.0.safetensors in ComfyUI/models/controlnet/
    """
    image_bytes = await file.read()
    wf = _load_workflow("sketch_to_lineart.json")

    uploaded_name = comfyui_client.upload_image_bytes(
        image_bytes, file.filename or "sketch.png"
    )
    for node in wf.values():
        if isinstance(node, dict) and node.get("class_type") == "LoadImage":
            node["inputs"]["image"] = uploaded_name

    return Response(content=_run(wf), media_type="image/png")


class GenerateRequest(BaseModel):
    prompt: str
    negative_prompt: str = _DEFAULT_NEGATIVE
    width: int = 1024
    height: int = 1024
    steps: int = 20
    seed: int = -1  # -1 = random


@router.post("/art/generate", summary="文字→圖片 (SDXL txt2img)")
def generate(req: GenerateRequest):
    """
    Generate an illustration from a text prompt via ComfyUI SDXL.
    Requires: AnythingXL_xl.safetensors in ComfyUI/models/checkpoints/
    """
    seed = req.seed if req.seed >= 0 else random.randint(0, 2**31 - 1)
    wf = _load_workflow("text_to_image.json")

    for node in wf.values():
        if not isinstance(node, dict):
            continue
        ct = node.get("class_type")
        inputs = node.get("inputs", {})
        if ct == "CLIPTextEncode":
            if inputs.get("text") == "__POSITIVE__":
                inputs["text"] = req.prompt
            elif inputs.get("text") == "__NEGATIVE__":
                inputs["text"] = req.negative_prompt
        elif ct == "EmptyLatentImage":
            inputs["width"] = req.width
            inputs["height"] = req.height
        elif ct == "KSampler":
            inputs["seed"] = seed
            inputs["steps"] = req.steps

    return Response(content=_run(wf), media_type="image/png")


def _inject_txt2img(wf: dict, prompt: str, negative: str, seed: int, steps: int = 20) -> None:
    """Inject runtime values into a text_to_image workflow in-place."""
    for node in wf.values():
        if not isinstance(node, dict):
            continue
        ct = node.get("class_type")
        inputs = node.get("inputs", {})
        if ct == "CLIPTextEncode":
            if inputs.get("text") == "__POSITIVE__":
                inputs["text"] = prompt
            elif inputs.get("text") == "__NEGATIVE__":
                inputs["text"] = negative
        elif ct == "KSampler":
            inputs["seed"] = seed
            inputs["steps"] = steps


@router.post("/art/compose", summary="草圖問答 → 構圖意見 + 參考圖")
async def compose(
    file: Annotated[UploadFile, File(description="草稿圖片")],
    question: str = Form(..., description="針對草圖的構圖問題"),
    model: str = Form(DEFAULT_VISION_MODEL),
):
    start_total = time.time()
    image_bytes = await file.read()

    # Step 1: Ollama vision → advice + SDXL prompt
    try:
        start_ollama = time.time()
        advice, sdxl_prompt = art_service.compose_ask(question, image_bytes, model=model)
        print(f"DEBUG: Ollama analysis took {time.time() - start_ollama:.2f}s", flush=True)
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))

    # Step 2: ComfyUI → reference image
    start_comfy = time.time()
    seed = random.randint(0, 2**31 - 1)
    wf = _load_workflow("text_to_image.json")
    _inject_txt2img(wf, sdxl_prompt, _DEFAULT_NEGATIVE, seed)
    image_data = _run(wf)
    print(f"DEBUG: ComfyUI generation took {time.time() - start_comfy:.2f}s", flush=True)

    # Step 3: Base64 encoding
    start_b64 = time.time()
    encoded_image = base64.b64encode(image_data).decode()
    print(f"DEBUG: B64 encoding took {time.time() - start_b64:.2f}s", flush=True)

    print(f"DEBUG: Total compose endpoint took {time.time() - start_total:.2f}s", flush=True)
    return {
        "advice": advice,
        "suggested_prompt": sdxl_prompt,
        "image": encoded_image,
        "seed": seed,
    }

